/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muhasebeproject;

import com.sun.jmx.snmp.SnmpDataTypeEnums;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 04.17
 *
 *
 * @author Şeyma
 */
public class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaEkran
     */
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    DefaultListModel dlm = new DefaultListModel();

    public AnaEkran() {
        initComponents();
        jList1.setModel(dlm);
        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{"urun adi", "birim", "miktar", "fiyat", "total", "Hesap Kod", "Gider Mer.", "YOK Kod"});
        jTable2.setModel(dtm2);
        dtm2.setColumnIdentifiers(new String[]{"urun adi", "birim", "miktar", "fiyat", "total", "Hesap Kod", "Gider Mer.", "YOK Kod"});
        dlm.removeAllElements();
        fakulte_box.removeAllItems();

        bolum_box.removeAllItems();
        uruncombobox.removeAllItems();
        birimcombobox.removeAllItems();


        /*
       !!!! BİLGİLER BURAYA GELİCEK TÜM TANIMLAMAARRRR !!!!
         */

 /*Fakulte.bolumler.add(eem);
          Fakulte.bolumler.add(blm);
          Fakulte.bolumler.add(psiko);*/
        for (int i = 0; i < Universite.fakulteler.size(); i++) {
            fakulte_box.addItem(Universite.fakulteler.get(i).ad);
        }
        for (int i = 0; i < Gider.urunListesi.size(); i++) {
            AnaEkran.uruncombobox.addItem(Gider.urunListesi.get(i).urun_adi);
        }
        for (int i = 0; i < Gider.onaylananBolumler.size(); i++) {
            dlm.addElement(Gider.onaylananBolumler.get(i).ad);
        }
        giderTopla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fakulte_box = new javax.swing.JComboBox<>();
        bolum_box = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        giderekleButon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_urunmiktar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_fiyat = new javax.swing.JTextField();
        birimcombobox = new javax.swing.JComboBox<>();
        uruncombobox = new javax.swing.JComboBox<>();
        duzenlebuton = new javax.swing.JButton();
        butonsil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        lbl_toplam = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        butceonayy = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fakulte_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fakulte", "Item 2", "Item 3", "Item 4" }));
        fakulte_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakulte_boxActionPerformed(evt);
            }
        });

        bolum_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bolum", "Item 2", "Item 3", "Item 4" }));
        bolum_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bolum_boxİtemStateChanged(evt);
            }
        });
        bolum_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bolum_boxMouseClicked(evt);
            }
        });
        bolum_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolum_boxActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        giderekleButon.setText("Gider Ekle");
        giderekleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giderekleButonActionPerformed(evt);
            }
        });

        jLabel1.setText("Fakülte");

        jLabel2.setText("Bolum");

        jLabel3.setText("Urun Adı");

        jLabel4.setText("Birim");

        jLabel5.setText("Miktar");

        jLabel6.setText("Fiyat");

        text_fiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_fiyatActionPerformed(evt);
            }
        });

        birimcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birimcomboboxActionPerformed(evt);
            }
        });

        uruncombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uruncomboboxActionPerformed(evt);
            }
        });

        duzenlebuton.setText("Duzenle");
        duzenlebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzenlebutonActionPerformed(evt);
            }
        });

        butonsil.setText("Sil");
        butonsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonsilActionPerformed(evt);
            }
        });

        jButton1.setText("Urun Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel9.setText("Silinen Giderler");

        jButton2.setText("Cıkıs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel10.setText("Onaylanan Giderler");

        jLabel12.setText("Toplam Gider");

        butceonayy.setText("Butce Onayla");
        butceonayy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butceonayyActionPerformed(evt);
            }
        });

        jButton3.setText("Onay Kaldır");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fakulte_box, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(bolum_box, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uruncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(birimcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(text_urunmiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(text_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(120, 120, 120)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(duzenlebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(giderekleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(butonsil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lbl_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(190, 190, 190))
                                    .addComponent(butceonayy, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 83, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addGap(61, 61, 61)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fakulte_box, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bolum_box, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_urunmiktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birimcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uruncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giderekleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(duzenlebuton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butonsil)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(butceonayy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(lbl_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fakulte_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakulte_boxActionPerformed
        // TODO add your handling code here:

        dtm.setRowCount(0);
        dtm2.setRowCount(0);
        bolum_box.removeAllItems();

        Fakulte temp = new Fakulte();
        for (int i = 0; i < Universite.fakulteler.size(); i++) {
            if (fakulte_box.getSelectedItem() != null) {
                if (Universite.fakulteler.get(i).ad.equals(fakulte_box.getSelectedItem().toString())) {
                    temp = Universite.fakulteler.get(i);
                }

            }
        }
        for (int i = 0; i < temp.bolumler.size(); i++) {
            bolum_box.addItem(temp.bolumler.get(i).ad);
        }


    }//GEN-LAST:event_fakulte_boxActionPerformed

    private void giderekleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giderekleButonActionPerformed
        // TODO add your handling code here:

        try {
            // String birim = text_birim.getText();
            int miktar = Integer.parseInt(text_urunmiktar.getText());
            int fiyat = Integer.parseInt(text_fiyat.getText());
            //String urunadi = text_urunadi.getText();
            Gider g = new Gider();
            g.birim = birimcombobox.getSelectedItem().toString();
            g.fiyat = fiyat;
            g.miktar = miktar;
            g.urun_adi = uruncombobox.getSelectedItem().toString();
            g.giderhesabı(g.fiyat, g.miktar);
            System.out.println("g totali" + g.toplamgider);

            Bolum bolumtemp = new Bolum();

            for (int i = 0; i < Universite.fakulteler.size(); i++) {
                for (int j = 0; j < Universite.fakulteler.get(i).bolumler.size(); j++) {
                    if (Universite.fakulteler.get(i).bolumler.get(j).ad.equals(bolum_box.getSelectedItem().toString())) {
                        Universite.fakulteler.get(i).bolumler.get(j).giderler.add(g);
                        //bolumtemp.giderler.add(g);
                        dtm.addRow(new Object[]{g.urun_adi, g.birim, String.valueOf(g.miktar),
                            String.valueOf(g.fiyat), String.valueOf(g.toplamgider)});

                        text_urunmiktar.setText("");
                        text_fiyat.setText("");

                    }
                }
            }

//            text_toplamGiderHesab.setText(String.valueOf(toplam));
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "lutfen fiyat ve miktari sayi giriniz");
        }

        giderTopla();


    }//GEN-LAST:event_giderekleButonActionPerformed
    void giderTopla() {
        try {
            int toplam = 0;
            Bolum bolumtemp1 = new Bolum();
            for (int i = 0; i < Universite.fakulteler.size(); i++) {
                for (int j = 0; j < Universite.fakulteler.get(i).bolumler.size(); j++) {

                    if (Universite.fakulteler.get(i).bolumler.get(j).ad.equals(bolum_box.getSelectedItem().toString())) {
                        bolumtemp1 = Universite.fakulteler.get(i).bolumler.get(j);
                    }
                }
            }
            for (int i = 0; i < bolumtemp1.giderler.size(); i++) {
                toplam += bolumtemp1.giderler.get(i).toplamgider;
            }
            lbl_toplam.setText(String.valueOf(toplam));

        } catch (NullPointerException n) {

        }
    }
    private void bolum_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolum_boxActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        dtm2.setRowCount(0);
        //dtm.getDataVector().removeAllElements();
        //dtm2.getDataVector().removeAllElements();
        Bolum tempb = new Bolum();
        Fakulte tempf = new Fakulte();

        for (int i = 0; i < Universite.fakulteler.size(); i++) {
            if (fakulte_box.getSelectedItem() != null) {
                if (Universite.fakulteler.get(i).ad.equals(fakulte_box.getSelectedItem().toString())) {
                    tempf = Universite.fakulteler.get(i);
                }
            }
        }
        for (int i = 0; i < tempf.bolumler.size(); i++) {
            if (bolum_box.getSelectedItem() != null) {
                if (tempf.bolumler.get(i).ad.equals(bolum_box.getSelectedItem().toString())) {
                    tempb = tempf.bolumler.get(i);

                }
            }
        }

        for (int i = 0; i < tempb.giderler.size(); i++) {
            if (tempb.giderler.get(i) != null) {
                // toplam += tempb.giderler.get(i).toplamgider;
                dtm.addRow(new String[]{tempb.giderler.get(i).urun_adi, tempb.giderler.get(i).birim, String.valueOf(tempb.giderler.get(i).miktar),
                    String.valueOf(tempb.giderler.get(i).fiyat), String.valueOf(tempb.giderler.get(i).toplamgider)});
            }
        }

        for (int i = 0; i < tempb.silinengiderler.size(); i++) {
            if (tempb.silinengiderler.get(i) != null) {
                dtm2.addRow(new String[]{tempb.silinengiderler.get(i).urun_adi, tempb.silinengiderler.get(i).birim, String.valueOf(tempb.silinengiderler.get(i).miktar),
                    String.valueOf(tempb.silinengiderler.get(i).fiyat), String.valueOf(tempb.silinengiderler.get(i).toplamgider)});

            }
        }
        giderTopla();


    }//GEN-LAST:event_bolum_boxActionPerformed

    private void bolum_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bolum_boxMouseClicked
        // TODO add your handling code here:
        /*  dtm.getDataVector().removeAllElements();    
        Bolum tempb=new Bolum();
        
        for (int i = 0; i < Universite.fakulteler.size(); i++) {
            for (int j = 0; j < Universite.fakulteler.get(i).bolumler.size(); j++) {
                if(Universite.fakulteler.get(i).bolumler.get(j).ad.equals(bolum_box.getSelectedItem().toString())){
                    tempb=Universite.fakulteler.get(i).bolumler.get(j);
                }
            }
        }
        
        for (int i = 0; i < tempb.giderler.size(); i++) {
            dtm.addRow(new String []{tempb.giderler.get(i).urun_adi, tempb.giderler.get(i).birim, String.valueOf(tempb.giderler.get(i).miktar),
                                     String.valueOf(tempb.giderler.get(i).fiyat), String.valueOf(tempb.giderler.get(i).toplamgider)});
            
        }*/


    }//GEN-LAST:event_bolum_boxMouseClicked

    private void text_fiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_fiyatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_fiyatActionPerformed

    private void bolum_boxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bolum_boxİtemStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_bolum_boxİtemStateChanged

    private void birimcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birimcomboboxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_birimcomboboxActionPerformed

    private void uruncomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uruncomboboxActionPerformed
        // TODO add your handling code here:
        //birim kutusunu dolduruyorum.
        birimcombobox.removeAllItems();

        String secilenurun = uruncombobox.getSelectedItem().toString();
        for (int i = 0; i < Gider.urunListesi.size(); i++) {
            if (Gider.urunListesi.get(i).urun_adi.equals(secilenurun)) {
                for (int j = 0; j < Gider.urunListesi.get(i).birimler.length; j++) {
                    if (Gider.urunListesi.get(i).birimler[j] != null) {
                        birimcombobox.addItem(Gider.urunListesi.get(i).birimler[j]);
                    }
                }
            }
        }


    }//GEN-LAST:event_uruncomboboxActionPerformed

    private void duzenlebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzenlebutonActionPerformed
        // TODO add your handling code here:
        //TOTALİN DEĞİŞMESİ LAZIM
        //OBEJEYE ATAMA AYAPICAKSIN

        int k = jTable1.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(uruncombobox.getSelectedItem(), k, 0);

        int total = Integer.parseInt(text_urunmiktar.getText()) * Integer.parseInt(text_fiyat.getText());
        if (k >= 0) {
            model.setValueAt(uruncombobox.getSelectedItem(), k, 0);
            model.setValueAt(birimcombobox.getSelectedItem(), k, 1);
            model.setValueAt(text_urunmiktar.getText(), k, 2);
            model.setValueAt(text_fiyat.getText(), k, 3);
            model.setValueAt(total, k, 4);
        }

        Bolum bolumtemp = new Bolum();
        for (int i = 0; i < Universite.fakulteler.size(); i++) {
            for (int j = 0; j < Universite.fakulteler.get(i).bolumler.size(); j++) {
                if (Universite.fakulteler.get(i).bolumler.get(j).ad.equals(bolum_box.getSelectedItem().toString())) {
                    bolumtemp = Universite.fakulteler.get(i).bolumler.get(j);
                    for (int l = 0; l < bolumtemp.giderler.size(); l++) {
                        if (bolumtemp.giderler.get(l).urun_adi.equals(model.getValueAt(k, 0).toString())) {
                            bolumtemp.giderler.get(l).urun_adi = uruncombobox.getSelectedItem().toString();
                            bolumtemp.giderler.get(l).birim = birimcombobox.getSelectedItem().toString();
                            bolumtemp.giderler.get(l).miktar = Integer.parseInt(text_urunmiktar.getText());
                            bolumtemp.giderler.get(l).fiyat = Integer.parseInt(text_fiyat.getText());
                            bolumtemp.giderler.get(l).giderhesabı(Integer.parseInt(text_urunmiktar.getText()), Integer.parseInt(text_fiyat.getText()));

                        }
                    }

                    text_urunmiktar.setText("");
                    text_fiyat.setText("");
                }
            }
        }

        System.out.println(model.getValueAt(k, 0).toString());
        giderTopla();


    }//GEN-LAST:event_duzenlebutonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            int selectRow = jTable1.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            text_urunmiktar.setText(model.getValueAt(selectRow, 2).toString());
            text_fiyat.setText(model.getValueAt(selectRow, 3).toString());
            uruncombobox.setSelectedItem(model.getValueAt(selectRow, 0).toString());
            birimcombobox.setSelectedItem(model.getValueAt(selectRow, 1).toString());
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void butonsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonsilActionPerformed

        int k = jTable1.getSelectedRow();

        dtm2.getDataVector().removeAllElements();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Bolum bolumtemp = new Bolum();
        for (int i = 0; i < Universite.fakulteler.size(); i++) {
            for (int j = 0; j < Universite.fakulteler.get(i).bolumler.size(); j++) {
                if (Universite.fakulteler.get(i).bolumler.get(j).ad.equals(bolum_box.getSelectedItem().toString())) {
                    bolumtemp = Universite.fakulteler.get(i).bolumler.get(j);
                    for (int l = 0; l < bolumtemp.giderler.size(); l++) {
                        if (bolumtemp.giderler.get(l).urun_adi.equals(model.getValueAt(k, 0).toString())) {
                            bolumtemp.silinengiderler.add(bolumtemp.giderler.get(l));
                            bolumtemp.giderler.remove(bolumtemp.giderler.get(l));
                            model.removeRow(k);
                        }
                    }
                    text_urunmiktar.setText("");
                    text_fiyat.setText("");
                }
            }
        }

        for (int i = 0; i < bolumtemp.silinengiderler.size(); i++) {
            dtm2.addRow(new Object[]{bolumtemp.silinengiderler.get(i).urun_adi, bolumtemp.silinengiderler.get(i).birim, String.valueOf(bolumtemp.silinengiderler.get(i).miktar),
                String.valueOf(bolumtemp.silinengiderler.get(i).fiyat), String.valueOf(bolumtemp.silinengiderler.get(i).toplamgider)});

        }

        giderTopla();


    }//GEN-LAST:event_butonsilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Urun_Ekle u = new Urun_Ekle();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Giris gi = new Giris();
        gi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butceonayyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butceonayyActionPerformed

        // TODO add your handling code here:
        Bolum bolumtemp = new Bolum();
        for (int i = 0; i < Universite.fakulteler.size(); i++) {
            for (int j = 0; j < Universite.fakulteler.get(i).bolumler.size(); j++) {
                if (Universite.fakulteler.get(i).bolumler.get(j).ad.equals(bolum_box.getSelectedItem().toString())) {
                    bolumtemp = Universite.fakulteler.get(i).bolumler.get(j);
                }
            }
        }
        int a = JOptionPane.showConfirmDialog(this, "Butceyi Onayliyor Musunuz?");
        if (a == JOptionPane.YES_OPTION) {
            if (Gider.onaylananBolumler.size() == 0) {
                dlm.addElement(bolumtemp.ad);
                Gider.onaylananBolumler.add(bolumtemp);

            } else {

                for (int i = 0; i < Gider.onaylananBolumler.size(); i++) {
                    if (Gider.onaylananBolumler.get(i).ad.equals(bolumtemp.ad)) {
                        JOptionPane.showMessageDialog(this, "Bu Butce Daha Once Onaylanmıstır");
                        return;
                    }

                }
                dlm.addElement(bolumtemp.ad);
                Gider.onaylananBolumler.add(bolumtemp);
            }

            // dlm.add(0, bolumtemp.ad);
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        }


    }//GEN-LAST:event_butceonayyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        /*try {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lütfen Listeden Bölüm Seciniz !");
        }*/
        try{
            
        
        System.out.println(Gider.onaylananBolumler.size());
        System.out.println(jList1.getSelectedValue());
        for (int i = 0; i < Gider.onaylananBolumler.size(); i++) {
            if (jList1.getSelectedValue() == null) {
                JOptionPane.showMessageDialog(this, "Lütfen Listeden Bölüm Seciniz");
            }
            if (jList1.getSelectedValue().equals(Gider.onaylananBolumler.get(i).ad)) {
                Gider.onaylananBolumler.remove(Gider.onaylananBolumler.get(i));
                dlm.removeElementAt(jList1.getSelectedIndex());
            }
        }
        }catch(NullPointerException e){
            
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> birimcombobox;
    private javax.swing.JComboBox<String> bolum_box;
    private javax.swing.JButton butceonayy;
    private javax.swing.JButton butonsil;
    private javax.swing.JButton duzenlebuton;
    static javax.swing.JComboBox<String> fakulte_box;
    private javax.swing.JButton giderekleButon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_toplam;
    private javax.swing.JTextField text_fiyat;
    private javax.swing.JTextField text_urunmiktar;
    static javax.swing.JComboBox<String> uruncombobox;
    // End of variables declaration//GEN-END:variables
}
