/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muhasebeproject;

/**
 *
 * @author Şeyma
 */
public class AnaGiris extends javax.swing.JFrame {

    /**
     * Creates new form AnaGiris
     */
    public AnaGiris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Yönetici Giris");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Fakulte Giris");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Giris g= new Giris();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FakulteGiris fg= new FakulteGiris();
        fg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaGiris().setVisible(true);
                Kullanıcı mudur = new Kullanıcı(1, 1, "ONAY");
                Kullanıcı.kullanıcılar.add(mudur);
                /* Kullanıcı Eem = new Kullanıcı(10, 3, "EEM");
        Kullanıcı mimar = new Kullanıcı(30, 2, "BLM");
        
        Kullanıcı.kullanıcılar.add(Eem);
        Kullanıcı.kullanıcılar.add(mimar);*/
                Fakulte edebiyat = new Fakulte("Edebiyat", 10);
                Fakulte muhendislik = new Fakulte("Muhendislik", 20);
                Fakulte mimaritasarım = new Fakulte("Mimarlik Ve Tasarım ", 30);
                Fakulte hukukfak = new Fakulte("Hukuk", 40);
                Fakulte iletisim = new Fakulte("Iletisim Fakultesi", 50);
                Universite u = new Universite();
                Universite.fakulteler.add(edebiyat);
                Universite.fakulteler.add(muhendislik);
                Universite.fakulteler.add(mimaritasarım);
                Universite.fakulteler.add(hukukfak);
                Universite.fakulteler.add(iletisim);

                Bolum blm = new Bolum("Bilgisayar Müh", 1);
                Bolum eem = new Bolum("Elektrik Müh", 2);
                Bolum bme = new Bolum("Biyomedikal Müh", 3);
                Bolum psiko = new Bolum("Psikoloji", 4);
                Bolum hukuk = new Bolum("Hukuk", 5);
                Bolum bilimTarihi = new Bolum("Bilim Tarihi", 6);
                Bolum mimarlik = new Bolum("Mimarlık", 7);
                Bolum icmimarlik = new Bolum("Ic Mimarlik", 8);
                Bolum temelegitim = new Bolum("Turk Egitim", 9);
                Bolum egitimbilimleri = new Bolum("Egitim Bilimleri", 10);

                muhendislik.bolumler.add(eem);
                muhendislik.bolumler.add(blm);
                muhendislik.bolumler.add(bme);
                edebiyat.bolumler.add(psiko);
                edebiyat.bolumler.add(bilimTarihi);
                mimaritasarım.bolumler.add(mimarlik);
                mimaritasarım.bolumler.add(icmimarlik);
                hukukfak.bolumler.add(hukuk);
                iletisim.bolumler.add(temelegitim);
                iletisim.bolumler.add(egitimbilimleri);

                Gider kagit = new Gider("kagit", "kg", 10, 10);
                kagit.giderhesabı(kagit.fiyat, kagit.miktar);
                Gider kalem = new Gider("kalem", "adet", 10, 2);
                kalem.giderhesabı(kalem.fiyat, kalem.miktar);
                Gider silgi = new Gider("silgi", "kutu", 1, 20);
                silgi.giderhesabı(silgi.fiyat, silgi.miktar);
                Gider soylesi = new Gider("soylesi", "adet", 1000, 1);
                soylesi.giderhesabı(soylesi.fiyat, soylesi.miktar);
                Gider masa = new Gider("masa", "adet", 120, 4);
                masa.giderhesabı(masa.fiyat, masa.miktar);
                Gider bilgisayar = new Gider("bilgisayar", "adet", 3000, 20);
                bilgisayar.giderhesabı(bilgisayar.fiyat, bilgisayar.miktar);
                Gider hoca = new Gider("Oğretim Gorevlisi", "adet", 1, 10000);

                Gider.urunListesi.add(kalem);
                Gider.urunListesi.add(kagit);
                Gider.urunListesi.add(soylesi);
                Gider.urunListesi.add(masa);
                Gider.urunListesi.add(bilgisayar);
                Gider.urunListesi.add(hoca);
                Gider.urunListesi.add(silgi);

                /* for (int i = 0; i < Gider.urunListesi.size(); i++) {
            uruncombobox.addItem(Gider.urunListesi.get(i).urun_adi);
        }*/
                String birimIsimleri[] = {"kutu", "kilo", "adet"};
                String birimIsimleri2[] = {"adet"};
                String birimIsımler3[] = {"Prof", "Doçent", "Dr.Ogretim Uyesi", "Arastırma Uyesi"};
                kagit.birimler = birimIsimleri;
                kalem.birimler = birimIsimleri;
                silgi.birimler = birimIsimleri;
                soylesi.birimler = birimIsimleri2;
                masa.birimler = birimIsimleri2;
                bilgisayar.birimler = birimIsimleri2;
                hoca.birimler = birimIsımler3;
                silgi.birimler = birimIsimleri;

                eem.giderler.add(kalem);
                blm.giderler.add(bilgisayar);
                bme.giderler.add(soylesi);
                psiko.giderler.add(silgi);
                psiko.giderler.add(kalem);
                psiko.giderler.add(kagit);
                bilimTarihi.giderler.add(soylesi);
                mimarlik.giderler.add(masa);
                mimarlik.giderler.add(kagit);
                icmimarlik.giderler.add(kalem);

                for (int i = 0; i < Gider.urunListesi.size(); i++) {
                    System.out.println(Gider.urunListesi.get(i).urun_adi);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
