/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muhasebeproject;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Şeyma
 */
public class BolumGiris extends javax.swing.JFrame {

    /**
     * Creates new form BolumGiris
     */
    DefaultTableModel dtm3 = new DefaultTableModel();

    public BolumGiris() {
        initComponents();

        jTable1.setModel(dtm3);
        jComboFakulte_Urun.removeAllItems();

        dtm3.setColumnIdentifiers(new String[]{"urun adi", "birim", "miktar", "fiyat", "total", "Hesap Kod", "Gider Mer.", "YOK Kod"});

        //jComboFakulte_Urun=AnaEkran.uruncombobox;
        for (int i = 0; i < Gider.urunListesi.size(); i++) {
            jComboFakulte_Urun.addItem(Gider.urunListesi.get(i).urun_adi);
        }
        for (int i = 0; i < FakulteGiris.fakulteGiris.bolumler.size(); i++) {
            jComboBolumler.addItem(FakulteGiris.fakulteGiris.bolumler.get(i).ad);
        }
        
        giderTopla();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboFakulte_Urun = new javax.swing.JComboBox<>();
        jComboFakulteBirim = new javax.swing.JComboBox<>();
        fakultemiktar = new javax.swing.JTextField();
        fakultefiyat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBolumler = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelonayy = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbltoplam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboFakulte_Urun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFakulte_UrunActionPerformed(evt);
            }
        });

        fakultemiktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakultemiktarActionPerformed(evt);
            }
        });

        fakultefiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakultefiyatActionPerformed(evt);
            }
        });

        jLabel1.setText("Urun Adi");

        jLabel2.setText("miktar");

        jLabel3.setText("fiyat");

        jLabel4.setText("Birim");

        jButton1.setText("Cıkıs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBolumler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBolumlerActionPerformed(evt);
            }
        });

        jButton2.setText("Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Düzenle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Bütçe Onaylanma Durumu :");

        jLabel6.setText("Toplam Gider");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelonayy, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBolumler, 0, 75, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboFakulte_Urun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboFakulteBirim, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(fakultemiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fakultefiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(248, 248, 248))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lbltoplam, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jComboBolumler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fakultefiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fakultemiktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboFakulteBirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboFakulte_Urun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbltoplam, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelonayy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel5)))
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        FakulteGiris fagiris = new FakulteGiris();
        fagiris.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
    void giderTopla() {
        try {
            int toplam = 0;
            Bolum bolumtemp1 = new Bolum();

            for (int j = 0; j < FakulteGiris.fakulteGiris.bolumler.size(); j++) {

                if (FakulteGiris.fakulteGiris.bolumler.get(j).ad.equals(jComboBolumler.getSelectedItem().toString())) {
                    bolumtemp1 = FakulteGiris.fakulteGiris.bolumler.get(j);
                }
            }

            for (int i = 0; i < bolumtemp1.giderler.size(); i++) {
                toplam += bolumtemp1.giderler.get(i).toplamgider;
            }
            lbltoplam.setText(String.valueOf(toplam));

        } catch (NullPointerException n) {

        }
    }

    private void jComboFakulte_UrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFakulte_UrunActionPerformed
        // TODO add your handling code here:
        jComboFakulteBirim.removeAllItems();

        String secilenurun = jComboFakulte_Urun.getSelectedItem().toString();
        for (int i = 0; i < Gider.urunListesi.size(); i++) {
            if (Gider.urunListesi.get(i).urun_adi.equals(secilenurun)) {
                for (int j = 0; j < Gider.urunListesi.get(i).birimler.length; j++) {
                    if (Gider.urunListesi.get(i).birimler[j] != null) {
                        jComboFakulteBirim.addItem(Gider.urunListesi.get(i).birimler[j]);
                    }
                }
            }
        }
    }//GEN-LAST:event_jComboFakulte_UrunActionPerformed

    private void fakultemiktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakultemiktarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fakultemiktarActionPerformed

    private void jComboBolumlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBolumlerActionPerformed
        // TODO add your handling code here:
        dtm3.setRowCount(0);
        Bolum tempb = new Bolum();
        for (int i = 0; i < FakulteGiris.fakulteGiris.bolumler.size(); i++) {
            if (jComboBolumler.getSelectedItem() != null) {
                if (FakulteGiris.fakulteGiris.bolumler.get(i).ad.equals(jComboBolumler.getSelectedItem().toString())) {
                    tempb = FakulteGiris.fakulteGiris.bolumler.get(i);

                }
            }
        }

        for (int i = 0; i < tempb.giderler.size(); i++) {
            if (tempb.giderler.get(i) != null) {
                // toplam += tempb.giderler.get(i).toplamgider;
                dtm3.addRow(new String[]{tempb.giderler.get(i).urun_adi, tempb.giderler.get(i).birim, String.valueOf(tempb.giderler.get(i).miktar),
                    String.valueOf(tempb.giderler.get(i).fiyat), String.valueOf(tempb.giderler.get(i).toplamgider)});
            }
        }

        for (int i = 0; i < Gider.onaylananBolumler.size(); i++) {
            if (jComboBolumler.getSelectedItem().toString().equals(Gider.onaylananBolumler.get(i).ad)) {
                jLabelonayy.setText("ONAYLANDI");
            } else {
                jLabelonayy.setText("ONAYLANMADI");
            }
        }
        giderTopla();

    }//GEN-LAST:event_jComboBolumlerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int miktar = Integer.parseInt(fakultemiktar.getText());
            int fiyat = Integer.parseInt(fakultefiyat.getText());
            //String urunadi = text_urunadi.getText();
            Gider g = new Gider();
            g.birim = jComboFakulteBirim.getSelectedItem().toString();
            g.fiyat = fiyat;
            g.miktar = miktar;
            g.urun_adi = jComboFakulte_Urun.getSelectedItem().toString();
            g.giderhesabı(g.fiyat, g.miktar);
            System.out.println("g totali" + g.toplamgider);

            Bolum bolumtemp = new Bolum();
            Fakulte f = FakulteGiris.fakulteGiris;
            for (int i = 0; i < f.bolumler.size(); i++) {
                if (f.bolumler.get(i).ad.equals(jComboBolumler.getSelectedItem().toString())) {
                    f.bolumler.get(i).giderler.add(g);
                    dtm3.addRow(new Object[]{g.urun_adi, g.birim, String.valueOf(g.miktar),
                        String.valueOf(g.fiyat), String.valueOf(g.toplamgider)});
                    fakultemiktar.setText("");
                    fakultefiyat.setText("");
                }
            }
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(this, "lutfen fiyat ve miktari sayi giriniz");
        }
        giderTopla();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int k = jTable1.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(jComboFakulte_Urun.getSelectedItem(), k, 0);

        int total = Integer.parseInt(fakultemiktar.getText()) * Integer.parseInt(fakultefiyat.getText());
        if (k >= 0) {
            model.setValueAt(jComboFakulte_Urun.getSelectedItem(), k, 0);
            model.setValueAt(jComboFakulteBirim.getSelectedItem(), k, 1);
            model.setValueAt(fakultemiktar.getText(), k, 2);
            model.setValueAt(fakultefiyat.getText(), k, 3);
            model.setValueAt(total, k, 4);
        }

        Bolum bolumtemp = new Bolum();
        Fakulte f = FakulteGiris.fakulteGiris;
        for (int i = 0; i < f.bolumler.size(); i++) {
            if (f.bolumler.get(i).ad.equals(jComboBolumler.getSelectedItem().toString())) {
                bolumtemp = f.bolumler.get(i);
                for (int l = 0; l < bolumtemp.giderler.size(); l++) {
                    if (bolumtemp.giderler.get(l).urun_adi.equals(model.getValueAt(k, 0).toString())) {
                        bolumtemp.giderler.get(l).urun_adi = jComboFakulte_Urun.getSelectedItem().toString();
                        bolumtemp.giderler.get(l).birim = jComboFakulteBirim.getSelectedItem().toString();
                        bolumtemp.giderler.get(l).miktar = Integer.parseInt(fakultemiktar.getText());
                        bolumtemp.giderler.get(l).fiyat = Integer.parseInt(fakultefiyat.getText());
                        bolumtemp.giderler.get(l).giderhesabı(Integer.parseInt(fakultemiktar.getText()), Integer.parseInt(fakultefiyat.getText()));

                    }
                }

                fakultemiktar.setText("");
                fakultefiyat.setText("");

            }

            System.out.println(model.getValueAt(k, 0).toString());
            giderTopla();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fakultefiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakultefiyatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fakultefiyatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int selectRow = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        fakultemiktar.setText(model.getValueAt(selectRow, 2).toString());
        fakultefiyat.setText(model.getValueAt(selectRow, 3).toString());
        jComboFakulte_Urun.setSelectedItem(model.getValueAt(selectRow, 0).toString());
        jComboFakulteBirim.setSelectedItem(model.getValueAt(selectRow, 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        int k = jTable1.getSelectedRow();

        //dtm3.getDataVector().removeAllElements();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Bolum bolumtemp = new Bolum();
        Fakulte f = FakulteGiris.fakulteGiris;
        for (int i = 0; i < f.bolumler.size(); i++) {
            if (f.bolumler.get(i).ad.equals(jComboBolumler.getSelectedItem().toString())) {
                bolumtemp = f.bolumler.get(i);
                for (int l = 0; l < bolumtemp.giderler.size(); l++) {
                    if (bolumtemp.giderler.get(l).urun_adi.equals(model.getValueAt(k, 0).toString())) {
                        bolumtemp.silinengiderler.add(bolumtemp.giderler.get(l));
                        bolumtemp.giderler.remove(bolumtemp.giderler.get(l));
                        model.removeRow(k);

                    }
                }

                fakultemiktar.setText("");
                fakultefiyat.setText("");

            }

        }giderTopla();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BolumGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BolumGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BolumGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BolumGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BolumGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fakultefiyat;
    private javax.swing.JTextField fakultemiktar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBolumler;
    private javax.swing.JComboBox<String> jComboFakulteBirim;
    private javax.swing.JComboBox<String> jComboFakulte_Urun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelonayy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbltoplam;
    // End of variables declaration//GEN-END:variables
}
